accept_button_list = [
    "ich stimme zu",
    "cookies akzeptieren",
    "i accept",
    "accept",
    "cookies zulassen",
    "ok",
    "jag accepterar alla cookies",
    "yes, i'm happy",
    "accept all cookies",
    "accepter",
    "i agree",
    "accept all",
    "agree",
    "zaakceptui wszystjie pliki cookie",
    "alle akzeptieren",
    "aceptar cookies",
    "accepter & fermer",
    "alle cookies akzeptieren",
    "hyväksy kaikki",
    "erforderliche und optionale cookies erlauben",
    "allow essential and optional cookies",
    "jag accepterar alla cookies",
    "zulassen",
    "accept cookies",
    "accetta tutti i cookie",
    "tout accepter",
    "weiter mit den empfohlenen cookies",
    "got it",
    "agree and access site",
    "yes i agree",
    "alle cookies zulassen",
    "accept & continue",
    "allow all cookies",
    "got it!",
    "agree & close",
    "aceptar todas",
    "rozumim",
    "jag förstår",
    "ok, agreed",
    "annehmen",
    "alle zulassen",
    "aceptar todas las cookies",
    "akzeptieren & schließen",
    "hyväksy kaikki evästeet",
    "save and close",
    "accept additional cookies",
    "allow all",
    "all ok",
    "ok, akzeptiere alles",
    "terima",
    "přijmout",
    "consent",
    "agree and close",
    "accept settings",
    "verstanden!",
    "acepto",
    "allow & close",
    "allow all cookies",
    "wählen sie alle",
    "accept and close",
    "cookies erlauben",
    "ok, i understand",
    "yes",
    "prihvati i zatvori",
    "enable all",
    "i understand",
    "alle annehmen",
    "continue to site",
    "ok, verstanden",
    "ich stimme der verwendung von cookies zu",
    "accepter la sélection",
    "zustimmen",
    "continue",
    "d'accord",
    "allow cookies",
    "aceitar todos",
    "aceptar",
    "permitir todas las cookies",
    "accepter tout",
    "accept recommended settings",
    "einwilligen mit personalisierung",
    "ok, i agree",
    "j'accepte",
    "accepter et fermer",
    "utilizar cookies opcionales",
    "accetto",
    "alle cookies gestatten",
    "i consent to cookies",
    "okay, thanks",
    "ok, tout accepter",
    "cookies akzeptieren und schließen",
    "zgadzam się",
    "entendi",
    "przejdź do serwisu",
    "akceptuję i przechodzę do serwisu",
    "verstanden",
    "akzeptieren"
]
